#!/bin/bash

# TODO: Each app gets its own user?

set -e

export site=$1
export site_type=${2:-rails}
export db_type=${3:-postgres}

export quickling_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export renv=${RAILS_ENV:-production}


sudo -u www q/repo "$1" "$2" "$3"
sudo q/hooks "$1" "$2" "$3"
sudo -u www q/srv "$1" "$2" "$3"
sudo q/nginx "$1" "$2" "$3"

sudo mkdir -p /etc/databases
sudo db/${db_type}.sh "$site"

set +e

cat <<DOC

************************************************************************

Ok. You're all set up! (I hope), anyway:
git clone ssh://www@$site/repo/$site.git # For new project
git remote add $site ssh://www@$site/repo/$site.git # For existing project

/etc/init/nginx restart # When you're ready & needed

DOC


