#!/bin/bash

quickling_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd /repo

renv=${RAILS_ENV:-production}

for repo in /repo/*.git; do
  cd "$repo/hooks/"

  echo "Copying hooks from $quickling_dir/hooks/*"
  for hook in "$quickling_dir"/hooks/*; do
    dst=`basename "$hook"`
    echo "$hook -> $repo/hooks/$dst"

    cat "$hook" | sed "s/%domain/$site/g" | sed "s/%renv/$renv/g" > "$dst";

    chown www:www $dst
    chmod 700 $dst
  done
done

echo "Done."
