#!/bin/bash

set -e

site=$1
site_type=${2:-rails}
db_type=${3:-postgres}

quickling_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

if [ "$site_type" != "ruby" ]; then
  if [ -e /etc/nginx/sites-avaailable/$site ]; then
    read -p "/etc/nginx/sites-available/$site already exists. Override? (y/N) " -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
    fi
  fi

  cat $quickling_dir/nginx-sites/$site_type | sed "s/%domain/$site/g" > /etc/nginx/sites-available/$site

  echo "Created nginx site. To enable:"
  echo "sudo ln -s /etc/nginx/sites-{available,enabled}/$site"
fi

